spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_kuang?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 配置环境，慢sql设置的是dev环境和test环境
  profiles:
    active: dev

#by zhengkai.blog.csdn.net
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0   # 已删除的，0(默认为1)
      logic-not-delete-value: 1 # 1是有效的  未删除的(默认为0)



